### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by MrConqueror** [DawntDev/MangaReader-App#2]
the app doesn't open it closes itself please update

**Comment by DawntDev** [comment]
@MrConqueror Hello, if this is because the service where the Backend was deployed has already been closed. If you wish, I can share the Backend repository with you, and you can make your own deployment.

**Comment by DawntDev** [comment]
Or the other, I ask you to wait for me while I find a service through which I can deploy the Backend.

**Comment by DawntDev** [comment]
I promise to spend time on it this week.

**Comment by DawntDev** [comment]
The issue is resolved in the last commit
